module.exports={
  '.js':'application/javascript',
  '.css':'text/css',
  '.png':'image/png',
  '.jpg':'image/jpg',
  '.jpeg':'image/jpeg',
  '.gif':'image/gif',
  '.svg':'image/svg+xml',
  '.ttf':'application/x-font-ttf',
  '.eot':'application/vnd.ms-fontobject'
};